trigger:
  branches:
    include:
      - feature/*

    exclude:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:

  - template: templates/install-dependencies.yaml

  - script: |
      TEMP_DIR=$(mktemp -d)  # Creates a temporary directory
      robot --variable BROWSER:chrome --variable OPTIONS:"--headless --disable-gpu --incognito --user-data-dir=${TEMP_DIR}" \
      --include new-feature --output results/logs/output_feature_test.xml --log results/logs/log_feature_test.html --report results/logs/report_feature_test.html tests/
    displayName: 'Run Tests tagged with new-feature'


  # Publish the Robot Framework reports as pipeline artifacts.
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/results/logs/'
      artifactName: 'robot-reports-feature'
    displayName: 'Publish Robot Framework Reports'


